<?php

module_load_include( 'inc', 'ocs_admin', 'ocs_account');

/***
* Implementation of hook_menu
*/
function ocs_admin_menu() {
    $items['helloworld'] = array(
        'title' => 'Hello World',
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'ocs_account_add_form'),
        'access arguments' => array('access content'),
    );

    $items['helloworld/%ctools_js/form'] = array(
        'title' => 'AJAX World',
        'page callback' => 'ocs_admin_modal',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['account/%ctools_js/select/%/%/%'] = array(
        'title' => 'Callback for adding a new account',
        'page callback' => 'ocs_account_select',
        'page arguments' => array(1,3,4,5),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    

    return $items;
}

/*
* Menu callback to say hello to the world
*/
function helloworld() {
    /*
    db_set_active('ocsdb');    // activation & execution same as explained above

    $result = db_select( 'ocs_customer')
        ->fields( 'ocs_customer', array( 'customer_id', 'customer_name'))
        ->execute();

    $output = "";
    while($record = $result->fetchAssoc()) {
        $output = $output.print_r($record, TRUE);
    }

    db_set_active('default'); // set back to original

    return $output;
    */
    ctools_include('ajax'); // Module  include the dependence it needs for ajax.
    ctools_include('modal');
    ctools_modal_add_js();

    $block['account'] = module_invoke( 'views', 'block_view', 'ocs_account-block2');
    $block['product'] = module_invoke( 'views', 'block_view', 'ocs_product-block');

    $form = drupal_get_form( 'ocs_account_add_form');
    $output = drupal_render( $form);

    return array(
        /*
        'first form' => array( 
            '#type' => 'markup',
            '#markup' => $output,
            '#prefix' => '<div id="ocs_account_add_form">',
            '#suffix' => '</div>',
            '#post_render' => array( 'ocs_account_add_form_post_render'),
            ),
        'kpr form' => array( 
            '#markup' => kpr( $table, TRUE),
            ),
        'kpr output' => array( 
            '#markup' => kpr( $output, TRUE),
            ),
            */
        'account' => $block['account']['content'],
        'kpr account' => array( 
            '#markup' => kpr( $block['account']['content'], TRUE),
            ),
            /*
        'product' => $block['product']['content'],
        */
    );
}

/*
** tried to implement modal popup to select customer or product
*/
function ocs_admin_modal( $js = NULL)
{
    if ( $js) {
        ctools_include('ajax');
        ctools_include('modal');
    }

    $form_state = array('ajax' => $js);
    $output = ctools_modal_form_wrapper('ocs_admin_test_form', $form_state);
    if ( $js) {
        if (!$output) {
            $output = array();
            $output[] = ajax_command_replace('#modal-message', '<div id="modal-message">' . $form_state['message'] . '</div>');
            $output[] = ctools_modal_command_dismiss();
        }

        print ajax_render($output);
    }
    else {
//        return $output;
        return ocs_admin_test_form( $form_state);
    }
}

function ocs_admin_test_form(&$form_state) {
    $form['text'] = array(
        '#type' => 'textfield',
        '#title' => t('Text'),
    );
    $block = module_invoke('views', 'block_view', 'ocs_product-block');
    $form['product']['block'] = $block['content'];
 
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}


/*
* Enable views to load this module
*/
function ocs_admin_views_api() {
      return array('api' => 3.0);
}

