<?php

module_load_include( 'inc', 'ocs_admin', 'ocs_account');

/***
* Implementation of hook_menu
*/
function ocs_admin_menu() {
    $items['helloworld'] = array(
        'title' => 'Hello World',
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'ocs_account_add_form'),
        'access arguments' => array('access content'),
    );

    $items['helloworld/%ctools_js/form'] = array(
        'title' => 'AJAX World',
        'page callback' => 'ocs_admin_modal',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['ocs_admin/%ctools_js/select/%/%/%'] = array(
        'title' => 'Callback for adding a new account',
        'page callback' => 'ocs_account_select',
        'page arguments' => array(1,3,4,5),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['ocs_admin/account/add/%'] = array(
        'title' => 'Add New Account',
        'page callback' => 'ocs_admin_account_add',
        'page arguments' => array(3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    

    return $items;
}

/*
* Menu callback to say hello to the world
*/
function helloworld() {
    /*
    db_set_active('ocsdb');    // activation & execution same as explained above

    $result = db_select( 'ocs_customer')
        ->fields( 'ocs_customer', array( 'customer_id', 'customer_name'))
        ->execute();

    $output = "";
    while($record = $result->fetchAssoc()) {
        $output = $output.print_r($record, TRUE);
    }

    db_set_active('default'); // set back to original

    return $output;
    */
    ctools_include('ajax'); // Module  include the dependence it needs for ajax.
    ctools_include('modal');
    ctools_modal_add_js();

    $block['account'] = module_invoke( 'views', 'block_view', 'ocs_account-block2');
    $block['product'] = module_invoke( 'views', 'block_view', 'ocs_product-block');

    $form = drupal_get_form( 'ocs_account_add_form');
    $output = drupal_render( $form);

    return array(
        /*
        'first form' => array( 
            '#type' => 'markup',
            '#markup' => $output,
            '#prefix' => '<div id="ocs_account_add_form">',
            '#suffix' => '</div>',
            '#post_render' => array( 'ocs_account_add_form_post_render'),
            ),
        'kpr form' => array( 
            '#markup' => kpr( $table, TRUE),
            ),
        'kpr output' => array( 
            '#markup' => kpr( $output, TRUE),
            ),
            */
        'account' => $block['account']['content'],
        'kpr account' => array( 
            '#markup' => kpr( $block['account']['content'], TRUE),
            ),
            /*
        'product' => $block['product']['content'],
        */
    );
}

/*
** tried to implement modal popup to select customer or product
*/
function ocs_admin_modal( $js = NULL)
{
    if ( $js) {
        ctools_include('ajax');
        ctools_include('modal');
    }

    $block = module_invoke( 'views', 'block_view', 'ocs_account-block');

    $form = ocs_admin_modal_submit_form( 'ocs_admin_modal_submit_form');
    $render = array(
        'title' => array(
            '#type' => 'markup',
            '#markup' => '<h2>Select Customer</h2>',
        ),

        'view' => $block['content'],

        'form' => $form,
    );

    if ( $js) {
        $command = array();
        $command = ctools_modal_form_render( $form_state, $render);
        print ajax_render( $command);
        exit;
    }
    else {
        return $render;
    }
}

function ocs_admin_modal_submit_form()
{
    /*
    $form['form_var'] = array(
        '#type' => 'markup',
        '#markup' => 'form',
        '#prefix' => '<div id="ocs_admin_modal_submit_form">',
        '#suffix' => '</div>',
        );
    */

    $form['submit'] = array(
        '#type' => 'button',
        '#value' => 'Submit',
    );

    return $form;
}

/*
* Enable views to load this module
*/
function ocs_admin_views_api() {
      return array('api' => 3.0);
}

