<?php

global $form_var;
$form_var = array();

/***
* Implementation of hook_menu
*/
function ocs_admin_menu() {
    $items['helloworld'] = array(
        'title' => 'Hello World',
        'page callback' => 'helloworld',
        'access arguments' => array('access content'),
        'file' => 'ocs_account.inc',
    );

    $items['helloworld/%ctools_js/form'] = array(
        'title' => 'AJAX World',
        'page callback' => 'ocs_admin_modal',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['account/%ctools_js/select/%/%/%'] = array(
        'title' => 'Callback for adding a new account',
        'page callback' => 'ocs_account_select',
        'page arguments' => array(1,3,4,5),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    

    return $items;
}

/*
* Menu callback to say hello to the world
*/
function helloworld() {
    /*
    db_set_active('ocsdb');    // activation & execution same as explained above

    $result = db_select( 'ocs_customer')
        ->fields( 'ocs_customer', array( 'customer_id', 'customer_name'))
        ->execute();

    $output = "";
    while($record = $result->fetchAssoc()) {
        $output = $output.print_r($record, TRUE);
    }

    db_set_active('default'); // set back to original

    return $output;
    */
    ctools_include('ajax'); // Module  include the dependence it needs for ajax.
    ctools_include('modal');
    ctools_modal_add_js();

    $block['account'] = module_invoke( 'views', 'block_view', 'ocs_account-block2');
    $block['product'] = module_invoke( 'views', 'block_view', 'ocs_product-block');

    $form = drupal_get_form( 'ocs_account_form');
    $output = drupal_render( $form);

    return array(
        /*
        'first form' => array( 
            '#type' => 'markup',
            '#markup' => $output,
            '#prefix' => '<div id="ocs_account_add_form">',
            '#suffix' => '</div>',
            '#post_render' => array( 'ocs_account_add_form_post_render'),
            ),
        'kpr form' => array( 
            '#markup' => kpr( $table, TRUE),
            ),
        'kpr output' => array( 
            '#markup' => kpr( $output, TRUE),
            ),
            */
        'account' => $block['account']['content'],
        'kpr account' => array( 
            '#markup' => kpr( $block['account']['content'], TRUE),
            ),
            /*
        'product' => $block['product']['content'],
        */
    );
}

function ocs_account_add_form_post_render($markup, $element)
{
    $block = module_invoke( 'views', 'block_view', 'ocs_account-block');
    $markup = str_replace( '<div id="customer_block"></div>', 
        drupal_render($block['content']), $markup);
    return $markup;
}

function ocs_account_add() 
{
    $form = drupal_get_form( 'ocs_account_form');
    $output = '<div id="ocs_account_add_form">' .  drupal_render( $form) . '</div>';

    return $output;

        /*
        'kpr account' => array( 
            '#markup' => kpr( $block['account']['content'], TRUE),
            ),
            */
}


function ocs_account_form( $form, &$form_state, $arg = NULL) 
{
    $form['customer'] = array(
        '#type' => 'fieldset',
        '#title' => t('Customer'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );

    $form['customer']['id'] = array(
        '#type' => 'textfield',
        '#title' => t('Customer ID'),
        '#default_value' => $arg['customer_id'],
    );

    $form['customer']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Customer Name'),
        '#default_value' => $arg['customer_name'],
    );

    $form['product'] = array(
        '#type' => 'fieldset',
        '#title' => t('Product'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );

    $form['product']['id'] = array(
        '#type' => 'textfield',
        '#title' => t('Product ID'),
        '#default_value' => $arg['product_id'],
    );

    $form['product']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Product Name'),
        '#default_value' => $arg['product_name'],
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}

function ocs_account_select( $js = NULL, $type = 'customer', $id = NULL, $name = NULL)
{
    global $form_var;

    $output = 'REPLACED'. kpr( $form_var, TRUE);

    if ( isset($id)) $form_var[ $type . '_id'] = $id;
    if ( isset($name)) $form_var[ $type . '_name'] = $name;

    $form = drupal_get_form( 'ocs_account_form', $form_var);

    $output .= '<div id="ocs_account_add_form">' . drupal_render( $form) . '</div>';
    if ( $js) {
        ctools_include('ajax');
        $commands = array();
        $commands[] = ajax_command_replace( '#ocs_account_add_form', $output);
        print ajax_render( $commands);
        exit;
    }
    else {
        return $output;
    }
}

function ocs_admin_modal( $js = NULL)
{
    if ( $js) {
        ctools_include('ajax');
        ctools_include('modal');
    }

    $form_state = array('ajax' => $js);
    $output = ctools_modal_form_wrapper('ocs_admin_test_form', $form_state);
    if ( $js) {
        if (!$output) {
            $output = array();
            $output[] = ajax_command_replace('#modal-message', '<div id="modal-message">' . $form_state['message'] . '</div>');
            $output[] = ctools_modal_command_dismiss();
        }

        print ajax_render($output);
    }
    else {
//        return $output;
        return ocs_admin_test_form( $form_state);
    }
}

function ocs_admin_test_form(&$form_state) {
    $form['text'] = array(
        '#type' => 'textfield',
        '#title' => t('Text'),
    );
    $block = module_invoke('views', 'block_view', 'ocs_product-block');
    $form['product']['block'] = $block['content'];
 
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}


/*
* Enable views to load this module
*/
function ocs_admin_views_api() {
      return array('api' => 3.0);
}


/*
**  Block APIs : hook_block_info()
//*/
//function ocs_admin_block_info() {
//    $blocks['ocs_admin_command_form'] = array(
//        'info' => t('OCS Admin command block'),
//        'status' => TRUE,
//        'region' => 'Content',
//        'cache' => DRUPAL_CACHE_PER_ROLE,   // default
//        'visibility' => BLOCK_VISIBILITY_LISTED,
//        'pages' => 'ocs-account',
//    );
//
//    return $blocks;
//}
//
///*
//**  hook_block_view()
//*/
//function ocs_admin_block_view($delta = '') {
//    switch ($delta) {
//        case 'ocs_admin_command_form':
//            $block['subjst'] = t('COMMAND Pannel');
////            $block['content'] = ocs_admin_command_form_block();
//            $block['content'] = t('<a href="@url">Add</a>', array( '@url' => url('ocs_account/form/add')));
//       break;
//    }
//
//    return $block;
//}
//
//function ocs_admin_command_form_block() {
//    $form['add'] = array(
//        '#type' => 'submit',
//        '#value' => 'Add',
//        '#process' => array( 'ocs_admin_command_form_add_submit'),
//    );
//    $form['del'] = array(
//        '#type' => 'submit',
//        '#value' => 'Delete',
//        '#submit' => array( 'ocs_admin_command_form_submit'),
//    );
//    return $form;
//}
//
//// submit handler for command form
//function ocs_admin_command_form_add_submit( $form, &$form_state) {
//    drupal_set_message(t('submitted'));
//}
//
//function ocs_admin_command_form_submit( $form, &$form_state) {
//    drupal_set_message(t('submitted'));
//}
//
//
//function ocs_admin_block_list_alter( &$blocks) {
//    foreach( $blocks as $bid => $block) {
//        if (($block->module == 'search') && ($block->delta == 'form')) {
//            unset( $blocks[$bid]);
//            $blocks[$bid] = $block;
//            break;
//        }
//    }
//}
